#pragma once

#include <stdint.h>

// Generated by model/train_seat_model.py.
static constexpr bool kSeatModelTrained = true;
static constexpr uint32_t kSeatModelVersionMajor = 1;
static constexpr uint32_t kSeatModelVersionMinor = 2;
static constexpr const char *kSeatModelVersion = "1.2";
static constexpr uint32_t kSeatModelFeatureCount = 64;
static constexpr int32_t kSeatModelBias = -142;
static constexpr int8_t kSeatModelWeights[kSeatModelFeatureCount] = {
      14,    4,  -11,    2,  -19,   12,   -5,    9,
      16,  -16,    7,   -2,   -6,   19,  -15,   -9,
       3,    3,   14,    9,   -6,   15,    5,   18,
      21,   15,  -20,  -39,  -51,  -26,    0,   11,
      10,  -35,   -9,   32,   -6,   15,   -9,  -14,
     -41,   11,    6,   24,    9,   16,   -3,  -12,
      -2,    9,   24,    2,  -12,   39,   -7,    8,
       7,    0,   -2,   -4,   -3,  -19,  -22,   23,
};
