#pragma once

#include <stdint.h>

// Generated by model/train_seat_model.py.
static constexpr bool kSeatModelTrained = true;
static constexpr uint32_t kSeatModelVersion = 1;
static constexpr uint32_t kSeatModelFeatureCount = 64;
static constexpr int32_t kSeatModelBias = 3489;
static constexpr int8_t kSeatModelWeights[kSeatModelFeatureCount] = {
       7,   13,  -20,  -44,  -14,   -5,  -11,  -23,
      15,   27,  -19,  -21,  -17,    3,  -12,  -16,
      12,    8,  -32,  -20,  -18,   -7,  -34,  -31,
      12,    5,  -27,   15,    7,   12,  -22,    2,
      22,    7,  -21,   16,    9,   16,  -24,    9,
      21,   12,   -9,   25,   39,   11,    8,   43,
       6,   20,    9,    4,    2,   14,    0,   22,
      -7,  -18,  -23,  -10,  -20,  -28,  -22,   27,
};
