#pragma once

#include <stdint.h>

// Generated by model/train_seat_model.py.
// The checked-in default is intentionally conservative: it marks the model as
// not trained so firmware will use ROI fallback until real seated/absent samples exist.
static constexpr bool kSeatModelTrained = false;
static constexpr uint32_t kSeatModelVersion = 1;
static constexpr uint32_t kSeatModelFeatureCount = 64;
static constexpr int32_t kSeatModelBias = 0;
static constexpr int8_t kSeatModelWeights[kSeatModelFeatureCount] = {
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
};
