; LEGACY fallback only.
; New feature development has moved to ../firmware-idf/.
[env:esp32-s3-n16r8-cam]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.arduino.memory_type = qio_opi
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.flash_mode = qio
board_build.psram_type = opi
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=0
  -D BOARD_HAS_PSRAM
lib_deps =
  olikraus/U8g2@^2.36.12
